package rj.cocacode.keybindings

val KEYBINDING_CONTEXTS = listOf(
    "Global",
    "Chat",
    "Autocomplete",
    "Confirmation",
    "Help",
    "Transcript",
    "HistorySearch",
    "Task",
    "ThemePicker",
    "Settings",
    "Tabs",
    "Attachments",
    "Footer",
    "MessageSelector",
    "DiffDialog",
    "ModelPicker",
    "Select",
    "Plugin"
)

val KEYBINDING_CONTEXT_DESCRIPTIONS = mapOf(
    "Global" to "Active everywhere, regardless of focus",
    "Chat" to "When the chat input is focused",
    "Autocomplete" to "When autocomplete menu is visible",
    "Confirmation" to "When a confirmation/permission dialog is shown",
    "Help" to "When the help overlay is open",
    "Transcript" to "When viewing the transcript",
    "HistorySearch" to "When searching command history (ctrl+r)",
    "Task" to "When a task/agent is running in the foreground",
    "ThemePicker" to "When the theme picker is open",
    "Settings" to "When the settings menu is open",
    "Tabs" to "When tab navigation is active",
    "Attachments" to "When navigating image attachments in a select dialog",
    "Footer" to "When footer indicators are focused",
    "MessageSelector" to "When the message selector (rewind) is open",
    "DiffDialog" to "When the diff dialog is open",
    "ModelPicker" to "When the model picker is open",
    "Select" to "When a select/list component is focused",
    "Plugin" to "When the plugin dialog is open"
)

val KEYBINDING_ACTIONS = listOf(
    "app:interrupt",
    "app:exit",
    "app:toggleTodos",
    "app:toggleTranscript",
    "app:toggleBrief",
    "app:toggleTeammatePreview",
    "app:toggleTerminal",
    "app:redraw",
    "app:globalSearch",
    "app:quickOpen",
    "history:search",
    "history:previous",
    "history:next",
    "chat:cancel",
    "chat:killAgents",
    "chat:cycleMode",
    "chat:modelPicker",
    "chat:fastMode",
    "chat:thinkingToggle",
    "chat:submit",
    "chat:newline",
    "chat:undo",
    "chat:externalEditor",
    "chat:stash",
    "chat:imagePaste",
    "chat:messageActions",
    "autocomplete:accept",
    "autocomplete:dismiss",
    "autocomplete:previous",
    "autocomplete:next",
    "confirm:yes",
    "confirm:no",
    "confirm:previous",
    "confirm:next",
    "confirm:nextField",
    "confirm:previousField",
    "confirm:cycleMode",
    "confirm:toggle",
    "confirm:toggleExplanation",
    "tabs:next",
    "tabs:previous",
    "transcript:toggleShowAll",
    "transcript:exit",
    "historySearch:next",
    "historySearch:accept",
    "historySearch:cancel",
    "historySearch:execute",
    "task:background",
    "theme:toggleSyntaxHighlighting",
    "help:dismiss",
    "attachments:next",
    "attachments:previous",
    "attachments:remove",
    "attachments:exit",
    "footer:up",
    "footer:down",
    "footer:next",
    "footer:previous",
    "footer:openSelected",
    "footer:clearSelection",
    "footer:close",
    "messageSelector:up",
    "messageSelector:down",
    "messageSelector:top",
    "messageSelector:bottom",
    "messageSelector:select",
    "diff:dismiss",
    "diff:previousSource",
    "diff:nextSource",
    "diff:back",
    "diff:viewDetails",
    "diff:previousFile",
    "diff:nextFile",
    "modelPicker:decreaseEffort",
    "modelPicker:increaseEffort",
    "select:next",
    "select:previous",
    "select:accept",
    "select:cancel",
    "plugin:toggle",
    "plugin:install",
    "permission:toggleDebug",
    "settings:search",
    "settings:retry",
    "settings:close",
    "voice:pushToTalk"
)
